name: Build and deploy to Netlify

on:
  push:
    branches:
      - master
    paths:
      - 'content/**'
      - 'template/**'
      - 'package-lock.json'
      - '.ecomplus.cd.json'
      - '.netlify/**'
      - '.github/workflows/build-and-deploy.yml'

jobs:
  build-and-deploy:
    name: Build Storefront and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      github.event.head_commit.message != 'Initial commit' &&
      !contains(github.event.head_commit.message, '[skip ci]')

    steps:
      - name: Set remote repo URL
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "url=https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" >> $GITHUB_OUTPUT
        id: remote_repo

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Get ISG state
        id: isg_state
        run: |
          if [ -f .isg ]; then
            echo "rand=$(cat .isg)" >> $GITHUB_OUTPUT
          else
            echo "rand=0" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: npm ci --only=production

      - name: Check last changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: changed_files

      - name: Run partial build
        env:
          CHANGED_FILES: ${{ steps.changed_files.outputs.all }}
        run: |
          IS_ECOMPLUS_CD=$(node -p "const f = JSON.parse('${CHANGED_FILES}'); f.length === 1 && f[0] === '.ecomplus.cd.json'");
          if [ $IS_ECOMPLUS_CD != false ] && [ -f .bundles.json ] && [ -f .deploy/publish/storefront.js ]; then
            BUILD_SLUG=$(node -p "require('./.ecomplus.cd.json').slug || false");
            if [ $BUILD_SLUG != false ]; then
              npm run build -- --prerender=index,$BUILD_SLUG --no-bundler;
              echo "isg=2" >> $GITHUB_OUTPUT
            else
              npm run build -- --prerender-limit=1000 --no-bundler;
              echo "isg=1" >> $GITHUB_OUTPUT
            fi
          else
            npm run build -- --prerender=index,app/index,search,404 --prerender-limit=300;
            echo "isg=0" >> $GITHUB_OUTPUT
          fi
        id: partial_build

      - name: Output ISG state
        id: new_isg_state
        env:
          ISG_ENUM: ${{ steps.partial_build.outputs.isg }}
        run: |
          if [ $ISG_ENUM != 0 ] || [ ! -f .isg ]; then
            ISG_STATE=$RANDOM;
            echo $ISG_STATE > .isg;
          else
            ISG_STATE=$(cat .isg);
          fi
          echo "rand=$ISG_STATE" >> $GITHUB_OUTPUT

      - name: Config Git and check diff
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add .isg .bundles.json content template
          (git diff-index --quiet HEAD && echo "diff=0" >> $GITHUB_OUTPUT) || echo "diff=1" >> $GITHUB_OUTPUT
        id: git_diff

      - name: Commit local file changes
        if: steps.git_diff.outputs.diff == 1
        run: |
          git commit -m 'chore(post-build): update template defaults, bundles and isg states [skip ci]'

      - name: Push changes
        if: steps.git_diff.outputs.diff == 1
        continue-on-error: true
        env:
          REMOTE_REPO: ${{ steps.remote_repo.outputs.url }}
        run: git push "${REMOTE_REPO}" HEAD:master --follow-tags

      - name: Setup output directory for Netlify
        run: |
          mkdir -p .deploy/publish
          cp -r dist/* .deploy/publish/ || true
          rm -rf .deploy/publish/netlify.toml
          cp -r .netlify/* .deploy/ || true
          cp -r template .deploy/functions/ssr/
          rm -rf .deploy/functions/ssr/template/public
          rm -rf .deploy/functions/ssr/template/scss
          cp -r content .deploy/functions/ssr/
          cp .bundles.json .deploy/functions/ssr/bundles.json
          mkdir -p .deploy/functions/ssr/template/pages/@ecomplus/storefront-template/template
          cp -r node_modules/@ecomplus/widget-* .deploy/functions/ssr/template/pages/@ecomplus/ 2>/dev/null || true
          cp -r node_modules/@ecomplus/storefront-template/template/pages .deploy/functions/ssr/template/pages/@ecomplus/storefront-template/template/ || true

      - name: Clear functions directory of node_modules
        continue-on-error: true
        run: find .deploy/functions -name node_modules -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Zip Lambda functions
        run: |
          npx zip-it-and-ship-it .deploy/functions .deploy/functions-zip
          rm -rf .deploy/functions

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: './.deploy/publish'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 15
